### ISSUE TITLE
When self-hosting bobcat, all commmands just return "Command not found"

### ISSUE THREAD

**Issue by 4444dogs** [crispy-cat/bobcat#5]
When self-hosting bobcat, all commands just return "Command not found" even though they exist on the main instance.

**Comment by crispy-cat** [comment]
Please check the "modules" section in the config -- it should look like this: 
![image](https://user-images.githubusercontent.com/30805430/184460644-fa29b2b9-9fd9-4c94-a636-24d50e61a276.png)

**Comment by 4444dogs** [comment]
> Please check the "modules" section in the config -- it should look like this: ![image](https://user-images.githubusercontent.com/30805430/184460644-fa29b2b9-9fd9-4c94-a636-24d50e61a276.png)

It does look like that but it still dosen't work.

**Comment by crispy-cat** [comment]
Can you run `node dist/index.js > output.txt` for about 15 seconds and upload the file here?

**Comment by 4444dogs** [comment]
> Can you run `node dist/index.js > output.txt` for about 15 seconds and upload the file here?

Output:
```


================================================================================

Loading Config...
[Bobcat][2022-08-19 20:56:05][-]:  Opening database...
[Bobcat][2022-08-19 20:56:05][-]:  Loading modules...
[Bobcat][2022-08-19 20:56:05][I]:  Found 0 modules
[Bobcat][2022-08-19 20:56:05][-]:  Listening for commands...
Bobcat> [Bobcat][2022-08-19 20:56:05][I]:  Logging into Revolt...
[Bobcat][2022-08-19 20:56:06][I]:  Ready!
[Bobcat][2022-08-19 20:56:06][I]:  Logged in
```

**Comment by crispy-cat** [comment]
It seems the modules are not being loaded. Could you tell me more about your system?

**Comment by 4444dogs** [comment]
Don't hurt me, but I am doing this on Windows 11. (Yes, I know it sucks. I just like gaming.) I have 32GB of RAM, a Ryzen 7 CPU, and a RTX 3050 OC edition.

**Comment by crispy-cat** [comment]
W*ndows could quite possibly be expecting \'s instead of /'s like every other system. Try changing them in the config file.

**Comment by 4444dogs** [comment]
Seems to work now that I did that
