### ISSUE TITLE
feature request: Remove me from blacklist!!!!

### ISSUE THREAD

**Issue by expertmanofficial** [crispy-cat/bobcat#8]
![image(5)](https://user-images.githubusercontent.com/119038242/203957877-63c359d9-89eb-4f1a-a835-1e022f002428.png)

**Comment by crispy-cat** [comment]
![image](https://user-images.githubusercontent.com/30805430/204058962-f622f947-10a3-44ec-be9d-1315d16497ee.png)

**Comment by expertmanofficial** [comment]
no sir I know that it is a rickroll

please remove me from blacklist
